branches:
  only:
    - master
sudo: required
dist: trusty
services:
 - docker
language: node_js
node_js:
 - '6.5'
git:
  submodules: false
before_install:
  - npm config set spin false
  - npm install -g npm
install:
  - npm install
before_script:
  - npm run compile
script:
  - npm test
after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - export CURR_VER=`cat package.json | grep version | tr -s " " ":" | cut -d "\"" -f4`
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./scripts/publish-docker.sh; fi'
deploy:
  provider: npm
  email: nater@naterkane.com
  api_key:
    secure: mNB2sNkUBK7IW/XyMEw91w0vf0z2iLyUvH4iSz7rmJJbpEMSg2QOzc2hH3UbwYjSE4xG1jwZ/c41lmH09pq4r1eciFOh2GzbzvZkzBhORF2gERoH0K/ibrsqRhlgnXNQvnbfXLzO+bK/Tw9TKlb64jGR325oGljURoyMhyKKnhF03abqqQKzs4+0vTfOkyXCxMaVIJKizVKGfBP7bkcefr0jFmPYJ91cRrv3gFuskl+DpHks3rowaOBioAQSLmoG7OVE07Bi0E+Dx5F+O1Vt3mP7184eMcgpfB27oizZTWLniG3laU+FFCRxvpbenTZHUXt734VGJHsNee52xmAsIRnM3PLNJvk1sKGEI8xofD33+MKIg5M58SgHEaHzYIb3Q7h3Ep7UbrRRgAzAvobQCAkaXdIfYteT4H4BoyUp0hJyD0mDJe0dcGIw9srf9o5ettofMJqWQSPAdhP6VC7uiFrN4og5zCzBoRTFu8MdZpyyy4Gl0gcGOEMdth9WjVyj0OEJCLVfz55unYt369VwnQ1HRwB656G0uhNZz8nRUN9psib+i88W1BRFI6JmAWmU/2sVM78oEiV+vFnWA7LUr66fDkH6qh1LvuCN0IQGaGzw2KeY+CYDsgWCpEcD6kvKmqIPj9aZhe3cB/cLT6vaamVkMjg7dCDbFzcvPnfgIQc=
  on:
    tags: true
    repo: tenon-io/tenon-cli
notifications:
  slack:
    secure: DzUTAxLJjRBGaKSq9eZTEHRha/Oxt9Agp8fGzhop131y4D9cTrxkj2SXw7AEaqfzB7WYll03kpBkXLPun5tzEEmoPzAQIsDDXGiyMavVs9m8w0nD6uGF579ltf3gSTn84eKOVpGcwn+O90idx9760kDnzpxZr0lLARDn7unir+AbAqgdK3YD7uvJ3a5ynzx8MbdNO7i9Ji80Z2ghjjTMd5YpW6oLyXKeI0GkiQ9kWvfFZjVfFX+BMiaWQ0oQ2WNczTJazBVLJdCi7dIjUSyZ66hQM28tYYjWl+NsPDr0OUqYzJbdteLhEW+3nK6IWEabmNAcp5wKXWTgH49+2Y77XRkCKW5lMz8bCTsWv+r3l5OtYjyBY6aT6kpWs7JTs3cPgEO2ZhFNuuShmdDNLqmQM6IKJqGO09t3/Dup/PQjV9IbCgo0Xsnnj95iHs7vNzFmeME39BGcPME7LV/fLxC2imGLCGYzGNRhy0WPsPNMw1RvNxVDMT79HyKQxB/hX7KqHZAY8BaH9dtHubIgGnnn2QppagTV05+n86V1xF980gjTxWBB2K3OT2qDS1oV3lPdDASdGrKhUR4bdAlqd3Ziq/eOLnaXH2zH/focsNM3go2xm17g8esKxDmYCObmH5Lr3pAxYj5byPFGmfNCwSr98eXzaeVO/25lPqeLpqy0ujg=
